### ISSUE TITLE
 can not found  CSScriptLibrary.dll

### ISSUE THREAD

**Issue by yuzd** [codingseb/CSharpRegexTools4Npp#3]
![image](https://images4.c-ctrip.com/target/0zb0q120008cir8hz1C0D.png)

![image](https://images4.c-ctrip.com/target/0zb6k120008cir7ng55BB.png)

**Comment by codingseb** [comment]
OK it's work on the machine where I develop CSharpRegexTools4Npp but not on my ohter PC. So I will look to correct that.

**Comment by yuzd** [comment]
thanks

**Comment by codingseb** [comment]
I just published version [1.1.6.0](https://github.com/codingseb/CSharpRegexTools4Npp/releases/tag/1.1.6.0).
It work again for me.
All dependencies are merged in the dll so everything that is needed should be there. The drawdown is that the plugin take now more space in memory.

**Comment by yuzd** [comment]
Nice job
